services:
  process-graph-db:
    image: postgres:18
    container_name: process-graph-db
    environment:
        POSTGRES_USER: process_graph_user
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: process_graph_dev
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/process-graph-db-data:/var/lib/postgresql

